FROM alpine:3.21@sha256:48b0309ca019d89d40f670aa1bc06e426dc0931948452e8491e3d65087abc07d

RUN apk add --no-cache bash coreutils kubectl python3 tar

WORKDIR /workspace
COPY hack/control-plane-backup.sh /workspace/hack/control-plane-backup.sh

ENTRYPOINT ["/bin/bash"]
