apiVersion: v1
kind: ConfigMap
metadata:
  name: servicer-delivery-repo
  namespace: servicer-system
data:
  ref: main
  branch: main
  path: generated/delivery
  commitName: Servicer
  commitEmail: servicer@platform.local
