apiVersion: v1
kind: ServiceAccount
metadata:
  name: servicer-manager
  namespace: servicer-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: servicer-bff
  namespace: servicer-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: servicer-webhook-bootstrap
  namespace: servicer-system
