apiVersion: v1
kind: Service
metadata:
  name: servicer-webhook-service
  namespace: servicer-system
spec:
  selector:
    app.kubernetes.io/name: manager
  ports:
    - name: https
      port: 443
      targetPort: 9443
